/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View.NhanVien.View;

import View.nhanVien.NhanVienCard;
import com.pro1041.dao.DAO_nhanVien;
import java.awt.Component;
import java.awt.GridLayout;
import java.awt.Panel;
import javax.swing.JPanel;
import Model.nhanVien;

/**
 *
 * @author hnhut
 */
public class nhanVien_InternalForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form nhanVien_InternalForm
     */
    public nhanVien_InternalForm() {
        initComponents();
        System.out.println("Select All");
        showList_nv();
//        setSize(1000, 700);

    }

    public void CreateSize(int width, int heigt) {
        setSize(width, HEIGHT);
    }

    public void showList_nv() {
        nhanVien_showList_container.removeAll();
        for (nhanVien nv : new DAO_nhanVien().getALL_nv()) {
            NhanVienCard nv_Card = new NhanVienCard(nv);
            nhanVien_showList_container.add(nv_Card);
        }
        nhanVien_showList_container.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nhanVien_Item8 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        nhanVien_data_ID8 = new javax.swing.JLabel();
        nhanVien_data_Name8 = new javax.swing.JLabel();
        nhanVien_data_Level8 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        nhanVien_data_Date8 = new javax.swing.JLabel();
        nhanVien_data_Sex8 = new javax.swing.JLabel();
        nhanVien_data_CCCD8 = new javax.swing.JLabel();
        nhanVien_data_SDT8 = new javax.swing.JLabel();
        nhanVien_funtion_Add8 = new javax.swing.JButton();
        nhanVien_function_Delete8 = new javax.swing.JButton();
        nhanVien_function_Edit8 = new javax.swing.JButton();
        nhanVien_function_Detail8 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        nhanVien_showList_tbP = new javax.swing.JPanel();
        showList_nav = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        nhanVien_showList_container = new javax.swing.JPanel();
        nhanVien_Item9 = new javax.swing.JPanel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        nhanVien_data_ID9 = new javax.swing.JLabel();
        nhanVien_data_Name9 = new javax.swing.JLabel();
        nhanVien_data_Level9 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        nhanVien_data_Date9 = new javax.swing.JLabel();
        nhanVien_data_Sex9 = new javax.swing.JLabel();
        nhanVien_data_CCCD9 = new javax.swing.JLabel();
        nhanVien_data_SDT9 = new javax.swing.JLabel();
        nhanVien_funtion_Add9 = new javax.swing.JButton();
        nhanVien_function_Delete9 = new javax.swing.JButton();
        nhanVien_function_Edit9 = new javax.swing.JButton();
        nhanVien_function_Detail9 = new javax.swing.JButton();
        nhanVien_Item10 = new javax.swing.JPanel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        nhanVien_data_ID10 = new javax.swing.JLabel();
        nhanVien_data_Name10 = new javax.swing.JLabel();
        nhanVien_data_Level10 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        nhanVien_data_Date10 = new javax.swing.JLabel();
        nhanVien_data_Sex10 = new javax.swing.JLabel();
        nhanVien_data_CCCD10 = new javax.swing.JLabel();
        nhanVien_data_SDT10 = new javax.swing.JLabel();
        nhanVien_funtion_Add10 = new javax.swing.JButton();
        nhanVien_function_Delete10 = new javax.swing.JButton();
        nhanVien_function_Edit10 = new javax.swing.JButton();
        nhanVien_function_Detail10 = new javax.swing.JButton();
        nhanVien_Item11 = new javax.swing.JPanel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        nhanVien_data_ID11 = new javax.swing.JLabel();
        nhanVien_data_Name11 = new javax.swing.JLabel();
        nhanVien_data_Level11 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        nhanVien_data_Date11 = new javax.swing.JLabel();
        nhanVien_data_Sex11 = new javax.swing.JLabel();
        nhanVien_data_CCCD11 = new javax.swing.JLabel();
        nhanVien_data_SDT11 = new javax.swing.JLabel();
        nhanVien_funtion_Add11 = new javax.swing.JButton();
        nhanVien_function_Delete11 = new javax.swing.JButton();
        nhanVien_function_Edit11 = new javax.swing.JButton();
        nhanVien_function_Detail11 = new javax.swing.JButton();
        nhanVien_Item12 = new javax.swing.JPanel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        nhanVien_data_ID12 = new javax.swing.JLabel();
        nhanVien_data_Name12 = new javax.swing.JLabel();
        nhanVien_data_Level12 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        nhanVien_data_Date12 = new javax.swing.JLabel();
        nhanVien_data_Sex12 = new javax.swing.JLabel();
        nhanVien_data_CCCD12 = new javax.swing.JLabel();
        nhanVien_data_SDT12 = new javax.swing.JLabel();
        nhanVien_funtion_Add12 = new javax.swing.JButton();
        nhanVien_function_Delete12 = new javax.swing.JButton();
        nhanVien_function_Edit12 = new javax.swing.JButton();
        nhanVien_function_Detail12 = new javax.swing.JButton();
        nhanVien_showData_tbP = new javax.swing.JPanel();

        nhanVien_Item8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/a11.jpg"))); // NOI18N

        jLabel63.setText("Mã nhân viên");

        jLabel64.setText("Họ tên nhân viên");

        jLabel65.setText("Chức vụ");

        nhanVien_data_ID8.setText("nv0221313");

        nhanVien_data_Name8.setText("HungocCho");

        nhanVien_data_Level8.setText("Quản lý");

        jSeparator9.setBackground(new java.awt.Color(51, 0, 51));
        jSeparator9.setOpaque(true);

        jLabel66.setText("Ngày sinh");

        jLabel67.setText("Giới Tính");

        jLabel68.setText("Căn cước công dân");

        jLabel69.setText("Số điện thoại");

        nhanVien_data_Date8.setText("2004-13-11");

        nhanVien_data_Sex8.setText("Nam");

        nhanVien_data_CCCD8.setText("020203030066");

        nhanVien_data_SDT8.setText("0123456789");

        nhanVien_funtion_Add8.setText("Add");

        nhanVien_function_Delete8.setText("Delete");

        nhanVien_function_Edit8.setText("Edit");

        nhanVien_function_Detail8.setText("Detail");

        javax.swing.GroupLayout nhanVien_Item8Layout = new javax.swing.GroupLayout(nhanVien_Item8);
        nhanVien_Item8.setLayout(nhanVien_Item8Layout);
        nhanVien_Item8Layout.setHorizontalGroup(
            nhanVien_Item8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nhanVien_Item8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel62)
                .addGap(18, 18, 18)
                .addGroup(nhanVien_Item8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nhanVien_Item8Layout.createSequentialGroup()
                        .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nhanVien_data_ID8))
                    .addGroup(nhanVien_Item8Layout.createSequentialGroup()
                        .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nhanVien_data_Name8))
                    .addGroup(nhanVien_Item8Layout.createSequentialGroup()
                        .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nhanVien_data_Level8)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(nhanVien_Item8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nhanVien_Item8Layout.createSequentialGroup()
                        .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nhanVien_data_Date8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nhanVien_funtion_Add8))
                    .addGroup(nhanVien_Item8Layout.createSequentialGroup()
                        .addGroup(nhanVien_Item8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nhanVien_Item8Layout.createSequentialGroup()
                                .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nhanVien_data_SDT8))
                            .addGroup(nhanVien_Item8Layout.createSequentialGroup()
                                .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nhanVien_data_CCCD8))
                            .addGroup(nhanVien_Item8Layout.createSequentialGroup()
                                .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nhanVien_data_Sex8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(nhanVien_Item8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nhanVien_function_Detail8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nhanVien_function_Delete8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nhanVien_function_Edit8, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        nhanVien_Item8Layout.setVerticalGroup(
            nhanVien_Item8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nhanVien_Item8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nhanVien_Item8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nhanVien_Item8Layout.createSequentialGroup()
                        .addGroup(nhanVien_Item8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel63)
                            .addComponent(nhanVien_data_ID8))
                        .addGap(18, 18, 18)
                        .addGroup(nhanVien_Item8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel64)
                            .addComponent(nhanVien_data_Name8))
                        .addGap(18, 18, 18)
                        .addGroup(nhanVien_Item8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel65)
                            .addComponent(nhanVien_data_Level8)))
                    .addComponent(jLabel62))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator9)
            .addGroup(nhanVien_Item8Layout.createSequentialGroup()
                .addGroup(nhanVien_Item8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nhanVien_Item8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel66)
                        .addComponent(nhanVien_data_Date8))
                    .addGroup(nhanVien_Item8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nhanVien_funtion_Add8)))
                .addGap(18, 18, 18)
                .addGroup(nhanVien_Item8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nhanVien_Item8Layout.createSequentialGroup()
                        .addGroup(nhanVien_Item8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel67)
                            .addComponent(nhanVien_data_Sex8))
                        .addGap(18, 18, 18)
                        .addGroup(nhanVien_Item8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel68)
                            .addComponent(nhanVien_data_CCCD8))
                        .addGap(18, 18, 18)
                        .addGroup(nhanVien_Item8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel69)
                            .addComponent(nhanVien_data_SDT8))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nhanVien_Item8Layout.createSequentialGroup()
                        .addComponent(nhanVien_function_Delete8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nhanVien_function_Edit8)
                        .addGap(18, 18, 18)
                        .addComponent(nhanVien_function_Detail8)
                        .addContainerGap())))
        );

        showList_nav.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel16.setText("Search");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Clone");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout showList_navLayout = new javax.swing.GroupLayout(showList_nav);
        showList_nav.setLayout(showList_navLayout);
        showList_navLayout.setHorizontalGroup(
            showList_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showList_navLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        showList_navLayout.setVerticalGroup(
            showList_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showList_navLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(showList_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nhanVien_showList_container.setLayout(new java.awt.GridLayout(0, 4));

        nhanVien_Item9.setBackground(new java.awt.Color(255, 255, 102));

        jLabel70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/a11.jpg"))); // NOI18N

        jLabel71.setText("Mã nhân viên");

        jLabel72.setText("Họ tên nhân viên");

        jLabel73.setText("Chức vụ");

        nhanVien_data_ID9.setText("nv0221313");

        nhanVien_data_Name9.setText("HungocCho");

        nhanVien_data_Level9.setText("Quản lý");

        jSeparator10.setBackground(new java.awt.Color(51, 0, 51));
        jSeparator10.setOpaque(true);

        jLabel74.setText("Ngày sinh");

        jLabel75.setText("Giới Tính");

        jLabel76.setText("Căn cước công dân");

        jLabel77.setText("Số điện thoại");

        nhanVien_data_Date9.setText("2004-13-11");

        nhanVien_data_Sex9.setText("Nam");

        nhanVien_data_CCCD9.setText("020203030066");

        nhanVien_data_SDT9.setText("0123456789");

        nhanVien_funtion_Add9.setText("Add");

        nhanVien_function_Delete9.setText("Delete");

        nhanVien_function_Edit9.setText("Edit");

        nhanVien_function_Detail9.setText("Detail");

        javax.swing.GroupLayout nhanVien_Item9Layout = new javax.swing.GroupLayout(nhanVien_Item9);
        nhanVien_Item9.setLayout(nhanVien_Item9Layout);
        nhanVien_Item9Layout.setHorizontalGroup(
            nhanVien_Item9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nhanVien_Item9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel70)
                .addGap(18, 18, 18)
                .addGroup(nhanVien_Item9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nhanVien_Item9Layout.createSequentialGroup()
                        .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nhanVien_data_ID9))
                    .addGroup(nhanVien_Item9Layout.createSequentialGroup()
                        .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nhanVien_data_Name9))
                    .addGroup(nhanVien_Item9Layout.createSequentialGroup()
                        .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nhanVien_data_Level9)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(nhanVien_Item9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nhanVien_Item9Layout.createSequentialGroup()
                        .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nhanVien_data_Date9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nhanVien_funtion_Add9))
                    .addGroup(nhanVien_Item9Layout.createSequentialGroup()
                        .addGroup(nhanVien_Item9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nhanVien_Item9Layout.createSequentialGroup()
                                .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nhanVien_data_SDT9))
                            .addGroup(nhanVien_Item9Layout.createSequentialGroup()
                                .addComponent(jLabel76, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nhanVien_data_CCCD9))
                            .addGroup(nhanVien_Item9Layout.createSequentialGroup()
                                .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nhanVien_data_Sex9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(nhanVien_Item9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nhanVien_function_Detail9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nhanVien_function_Delete9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nhanVien_function_Edit9, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        nhanVien_Item9Layout.setVerticalGroup(
            nhanVien_Item9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nhanVien_Item9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nhanVien_Item9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nhanVien_Item9Layout.createSequentialGroup()
                        .addGroup(nhanVien_Item9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel71)
                            .addComponent(nhanVien_data_ID9))
                        .addGap(18, 18, 18)
                        .addGroup(nhanVien_Item9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel72)
                            .addComponent(nhanVien_data_Name9))
                        .addGap(18, 18, 18)
                        .addGroup(nhanVien_Item9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel73)
                            .addComponent(nhanVien_data_Level9)))
                    .addComponent(jLabel70))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator10)
            .addGroup(nhanVien_Item9Layout.createSequentialGroup()
                .addGroup(nhanVien_Item9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nhanVien_Item9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel74)
                        .addComponent(nhanVien_data_Date9))
                    .addGroup(nhanVien_Item9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nhanVien_funtion_Add9)))
                .addGap(18, 18, 18)
                .addGroup(nhanVien_Item9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nhanVien_Item9Layout.createSequentialGroup()
                        .addGroup(nhanVien_Item9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel75)
                            .addComponent(nhanVien_data_Sex9))
                        .addGap(18, 18, 18)
                        .addGroup(nhanVien_Item9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel76)
                            .addComponent(nhanVien_data_CCCD9))
                        .addGap(18, 18, 18)
                        .addGroup(nhanVien_Item9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel77)
                            .addComponent(nhanVien_data_SDT9))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nhanVien_Item9Layout.createSequentialGroup()
                        .addComponent(nhanVien_function_Delete9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nhanVien_function_Edit9)
                        .addGap(18, 18, 18)
                        .addComponent(nhanVien_function_Detail9)
                        .addContainerGap())))
        );

        nhanVien_showList_container.add(nhanVien_Item9);

        nhanVien_Item10.setBackground(new java.awt.Color(255, 255, 102));

        jLabel78.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/a11.jpg"))); // NOI18N

        jLabel79.setText("Mã nhân viên");

        jLabel80.setText("Họ tên nhân viên");

        jLabel81.setText("Chức vụ");

        nhanVien_data_ID10.setText("nv0221313");

        nhanVien_data_Name10.setText("HungocCho");

        nhanVien_data_Level10.setText("Quản lý");

        jSeparator11.setBackground(new java.awt.Color(51, 0, 51));
        jSeparator11.setOpaque(true);

        jLabel82.setText("Ngày sinh");

        jLabel83.setText("Giới Tính");

        jLabel84.setText("Căn cước công dân");

        jLabel85.setText("Số điện thoại");

        nhanVien_data_Date10.setText("2004-13-11");

        nhanVien_data_Sex10.setText("Nam");

        nhanVien_data_CCCD10.setText("020203030066");

        nhanVien_data_SDT10.setText("0123456789");

        nhanVien_funtion_Add10.setText("Add");

        nhanVien_function_Delete10.setText("Delete");

        nhanVien_function_Edit10.setText("Edit");

        nhanVien_function_Detail10.setText("Detail");

        javax.swing.GroupLayout nhanVien_Item10Layout = new javax.swing.GroupLayout(nhanVien_Item10);
        nhanVien_Item10.setLayout(nhanVien_Item10Layout);
        nhanVien_Item10Layout.setHorizontalGroup(
            nhanVien_Item10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nhanVien_Item10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel78)
                .addGap(18, 18, 18)
                .addGroup(nhanVien_Item10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nhanVien_Item10Layout.createSequentialGroup()
                        .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nhanVien_data_ID10))
                    .addGroup(nhanVien_Item10Layout.createSequentialGroup()
                        .addComponent(jLabel80, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nhanVien_data_Name10))
                    .addGroup(nhanVien_Item10Layout.createSequentialGroup()
                        .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nhanVien_data_Level10)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(nhanVien_Item10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nhanVien_Item10Layout.createSequentialGroup()
                        .addComponent(jLabel82, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nhanVien_data_Date10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nhanVien_funtion_Add10))
                    .addGroup(nhanVien_Item10Layout.createSequentialGroup()
                        .addGroup(nhanVien_Item10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nhanVien_Item10Layout.createSequentialGroup()
                                .addComponent(jLabel85, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nhanVien_data_SDT10))
                            .addGroup(nhanVien_Item10Layout.createSequentialGroup()
                                .addComponent(jLabel84, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nhanVien_data_CCCD10))
                            .addGroup(nhanVien_Item10Layout.createSequentialGroup()
                                .addComponent(jLabel83, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nhanVien_data_Sex10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(nhanVien_Item10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nhanVien_function_Detail10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nhanVien_function_Delete10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nhanVien_function_Edit10, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        nhanVien_Item10Layout.setVerticalGroup(
            nhanVien_Item10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nhanVien_Item10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nhanVien_Item10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nhanVien_Item10Layout.createSequentialGroup()
                        .addGroup(nhanVien_Item10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel79)
                            .addComponent(nhanVien_data_ID10))
                        .addGap(18, 18, 18)
                        .addGroup(nhanVien_Item10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel80)
                            .addComponent(nhanVien_data_Name10))
                        .addGap(18, 18, 18)
                        .addGroup(nhanVien_Item10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel81)
                            .addComponent(nhanVien_data_Level10)))
                    .addComponent(jLabel78))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator11)
            .addGroup(nhanVien_Item10Layout.createSequentialGroup()
                .addGroup(nhanVien_Item10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nhanVien_Item10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel82)
                        .addComponent(nhanVien_data_Date10))
                    .addGroup(nhanVien_Item10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nhanVien_funtion_Add10)))
                .addGap(18, 18, 18)
                .addGroup(nhanVien_Item10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nhanVien_Item10Layout.createSequentialGroup()
                        .addGroup(nhanVien_Item10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel83)
                            .addComponent(nhanVien_data_Sex10))
                        .addGap(18, 18, 18)
                        .addGroup(nhanVien_Item10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel84)
                            .addComponent(nhanVien_data_CCCD10))
                        .addGap(18, 18, 18)
                        .addGroup(nhanVien_Item10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel85)
                            .addComponent(nhanVien_data_SDT10))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nhanVien_Item10Layout.createSequentialGroup()
                        .addComponent(nhanVien_function_Delete10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nhanVien_function_Edit10)
                        .addGap(18, 18, 18)
                        .addComponent(nhanVien_function_Detail10)
                        .addContainerGap())))
        );

        nhanVien_showList_container.add(nhanVien_Item10);

        nhanVien_Item11.setBackground(new java.awt.Color(255, 255, 102));

        jLabel86.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/a11.jpg"))); // NOI18N

        jLabel87.setText("Mã nhân viên");

        jLabel88.setText("Họ tên nhân viên");

        jLabel89.setText("Chức vụ");

        nhanVien_data_ID11.setText("nv0221313");

        nhanVien_data_Name11.setText("HungocCho");

        nhanVien_data_Level11.setText("Quản lý");

        jSeparator12.setBackground(new java.awt.Color(51, 0, 51));
        jSeparator12.setOpaque(true);

        jLabel90.setText("Ngày sinh");

        jLabel91.setText("Giới Tính");

        jLabel92.setText("Căn cước công dân");

        jLabel93.setText("Số điện thoại");

        nhanVien_data_Date11.setText("2004-13-11");

        nhanVien_data_Sex11.setText("Nam");

        nhanVien_data_CCCD11.setText("020203030066");

        nhanVien_data_SDT11.setText("0123456789");

        nhanVien_funtion_Add11.setText("Add");

        nhanVien_function_Delete11.setText("Delete");

        nhanVien_function_Edit11.setText("Edit");

        nhanVien_function_Detail11.setText("Detail");

        javax.swing.GroupLayout nhanVien_Item11Layout = new javax.swing.GroupLayout(nhanVien_Item11);
        nhanVien_Item11.setLayout(nhanVien_Item11Layout);
        nhanVien_Item11Layout.setHorizontalGroup(
            nhanVien_Item11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nhanVien_Item11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel86)
                .addGap(18, 18, 18)
                .addGroup(nhanVien_Item11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nhanVien_Item11Layout.createSequentialGroup()
                        .addComponent(jLabel87, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nhanVien_data_ID11))
                    .addGroup(nhanVien_Item11Layout.createSequentialGroup()
                        .addComponent(jLabel88, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nhanVien_data_Name11))
                    .addGroup(nhanVien_Item11Layout.createSequentialGroup()
                        .addComponent(jLabel89, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nhanVien_data_Level11)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(nhanVien_Item11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nhanVien_Item11Layout.createSequentialGroup()
                        .addComponent(jLabel90, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nhanVien_data_Date11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nhanVien_funtion_Add11))
                    .addGroup(nhanVien_Item11Layout.createSequentialGroup()
                        .addGroup(nhanVien_Item11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nhanVien_Item11Layout.createSequentialGroup()
                                .addComponent(jLabel93, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nhanVien_data_SDT11))
                            .addGroup(nhanVien_Item11Layout.createSequentialGroup()
                                .addComponent(jLabel92, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nhanVien_data_CCCD11))
                            .addGroup(nhanVien_Item11Layout.createSequentialGroup()
                                .addComponent(jLabel91, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nhanVien_data_Sex11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(nhanVien_Item11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nhanVien_function_Detail11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nhanVien_function_Delete11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nhanVien_function_Edit11, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        nhanVien_Item11Layout.setVerticalGroup(
            nhanVien_Item11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nhanVien_Item11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nhanVien_Item11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nhanVien_Item11Layout.createSequentialGroup()
                        .addGroup(nhanVien_Item11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel87)
                            .addComponent(nhanVien_data_ID11))
                        .addGap(18, 18, 18)
                        .addGroup(nhanVien_Item11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel88)
                            .addComponent(nhanVien_data_Name11))
                        .addGap(18, 18, 18)
                        .addGroup(nhanVien_Item11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel89)
                            .addComponent(nhanVien_data_Level11)))
                    .addComponent(jLabel86))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator12)
            .addGroup(nhanVien_Item11Layout.createSequentialGroup()
                .addGroup(nhanVien_Item11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nhanVien_Item11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel90)
                        .addComponent(nhanVien_data_Date11))
                    .addGroup(nhanVien_Item11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nhanVien_funtion_Add11)))
                .addGap(18, 18, 18)
                .addGroup(nhanVien_Item11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nhanVien_Item11Layout.createSequentialGroup()
                        .addGroup(nhanVien_Item11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel91)
                            .addComponent(nhanVien_data_Sex11))
                        .addGap(18, 18, 18)
                        .addGroup(nhanVien_Item11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel92)
                            .addComponent(nhanVien_data_CCCD11))
                        .addGap(18, 18, 18)
                        .addGroup(nhanVien_Item11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel93)
                            .addComponent(nhanVien_data_SDT11))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nhanVien_Item11Layout.createSequentialGroup()
                        .addComponent(nhanVien_function_Delete11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nhanVien_function_Edit11)
                        .addGap(18, 18, 18)
                        .addComponent(nhanVien_function_Detail11)
                        .addContainerGap())))
        );

        nhanVien_showList_container.add(nhanVien_Item11);

        nhanVien_Item12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel94.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/a11.jpg"))); // NOI18N

        jLabel95.setText("Mã nhân viên");

        jLabel96.setText("Họ tên nhân viên");

        jLabel97.setText("Chức vụ");

        nhanVien_data_ID12.setText("nv0221313");

        nhanVien_data_Name12.setText("HungocCho");

        nhanVien_data_Level12.setText("Quản lý");

        jSeparator13.setBackground(new java.awt.Color(51, 0, 51));
        jSeparator13.setOpaque(true);

        jLabel98.setText("Ngày sinh");

        jLabel99.setText("Giới Tính");

        jLabel100.setText("Căn cước công dân");

        jLabel101.setText("Số điện thoại");

        nhanVien_data_Date12.setText("2004-13-11");

        nhanVien_data_Sex12.setText("Nam");

        nhanVien_data_CCCD12.setText("020203030066");

        nhanVien_data_SDT12.setText("0123456789");

        nhanVien_funtion_Add12.setText("Add");

        nhanVien_function_Delete12.setText("Delete");

        nhanVien_function_Edit12.setText("Edit");

        nhanVien_function_Detail12.setText("Detail");

        javax.swing.GroupLayout nhanVien_Item12Layout = new javax.swing.GroupLayout(nhanVien_Item12);
        nhanVien_Item12.setLayout(nhanVien_Item12Layout);
        nhanVien_Item12Layout.setHorizontalGroup(
            nhanVien_Item12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nhanVien_Item12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel94)
                .addGap(18, 18, 18)
                .addGroup(nhanVien_Item12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nhanVien_Item12Layout.createSequentialGroup()
                        .addComponent(jLabel95, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nhanVien_data_ID12))
                    .addGroup(nhanVien_Item12Layout.createSequentialGroup()
                        .addComponent(jLabel96, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nhanVien_data_Name12))
                    .addGroup(nhanVien_Item12Layout.createSequentialGroup()
                        .addComponent(jLabel97, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nhanVien_data_Level12)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(nhanVien_Item12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nhanVien_Item12Layout.createSequentialGroup()
                        .addComponent(jLabel98, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nhanVien_data_Date12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nhanVien_funtion_Add12))
                    .addGroup(nhanVien_Item12Layout.createSequentialGroup()
                        .addGroup(nhanVien_Item12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nhanVien_Item12Layout.createSequentialGroup()
                                .addComponent(jLabel101, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nhanVien_data_SDT12))
                            .addGroup(nhanVien_Item12Layout.createSequentialGroup()
                                .addComponent(jLabel100, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nhanVien_data_CCCD12))
                            .addGroup(nhanVien_Item12Layout.createSequentialGroup()
                                .addComponent(jLabel99, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nhanVien_data_Sex12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(nhanVien_Item12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nhanVien_function_Detail12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nhanVien_function_Delete12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nhanVien_function_Edit12, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        nhanVien_Item12Layout.setVerticalGroup(
            nhanVien_Item12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nhanVien_Item12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nhanVien_Item12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nhanVien_Item12Layout.createSequentialGroup()
                        .addGroup(nhanVien_Item12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel95)
                            .addComponent(nhanVien_data_ID12))
                        .addGap(18, 18, 18)
                        .addGroup(nhanVien_Item12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel96)
                            .addComponent(nhanVien_data_Name12))
                        .addGap(18, 18, 18)
                        .addGroup(nhanVien_Item12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel97)
                            .addComponent(nhanVien_data_Level12)))
                    .addComponent(jLabel94))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator13)
            .addGroup(nhanVien_Item12Layout.createSequentialGroup()
                .addGroup(nhanVien_Item12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nhanVien_Item12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel98)
                        .addComponent(nhanVien_data_Date12))
                    .addGroup(nhanVien_Item12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nhanVien_funtion_Add12)))
                .addGap(18, 18, 18)
                .addGroup(nhanVien_Item12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nhanVien_Item12Layout.createSequentialGroup()
                        .addGroup(nhanVien_Item12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel99)
                            .addComponent(nhanVien_data_Sex12))
                        .addGap(18, 18, 18)
                        .addGroup(nhanVien_Item12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel100)
                            .addComponent(nhanVien_data_CCCD12))
                        .addGap(18, 18, 18)
                        .addGroup(nhanVien_Item12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel101)
                            .addComponent(nhanVien_data_SDT12))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nhanVien_Item12Layout.createSequentialGroup()
                        .addComponent(nhanVien_function_Delete12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nhanVien_function_Edit12)
                        .addGap(18, 18, 18)
                        .addComponent(nhanVien_function_Detail12)
                        .addContainerGap())))
        );

        nhanVien_showList_container.add(nhanVien_Item12);

        jScrollPane1.setViewportView(nhanVien_showList_container);

        javax.swing.GroupLayout nhanVien_showList_tbPLayout = new javax.swing.GroupLayout(nhanVien_showList_tbP);
        nhanVien_showList_tbP.setLayout(nhanVien_showList_tbPLayout);
        nhanVien_showList_tbPLayout.setHorizontalGroup(
            nhanVien_showList_tbPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(showList_nav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(nhanVien_showList_tbPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 987, Short.MAX_VALUE)
                .addContainerGap())
        );
        nhanVien_showList_tbPLayout.setVerticalGroup(
            nhanVien_showList_tbPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nhanVien_showList_tbPLayout.createSequentialGroup()
                .addComponent(showList_nav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Nhân Viên", nhanVien_showList_tbP);

        javax.swing.GroupLayout nhanVien_showData_tbPLayout = new javax.swing.GroupLayout(nhanVien_showData_tbP);
        nhanVien_showData_tbP.setLayout(nhanVien_showData_tbPLayout);
        nhanVien_showData_tbPLayout.setHorizontalGroup(
            nhanVien_showData_tbPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 999, Short.MAX_VALUE)
        );
        nhanVien_showData_tbPLayout.setVerticalGroup(
            nhanVien_showData_tbPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Thống kê", nhanVien_showData_tbP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel nhanVien_Item10;
    private javax.swing.JPanel nhanVien_Item11;
    private javax.swing.JPanel nhanVien_Item12;
    private javax.swing.JPanel nhanVien_Item8;
    private javax.swing.JPanel nhanVien_Item9;
    private javax.swing.JLabel nhanVien_data_CCCD10;
    private javax.swing.JLabel nhanVien_data_CCCD11;
    private javax.swing.JLabel nhanVien_data_CCCD12;
    private javax.swing.JLabel nhanVien_data_CCCD8;
    private javax.swing.JLabel nhanVien_data_CCCD9;
    private javax.swing.JLabel nhanVien_data_Date10;
    private javax.swing.JLabel nhanVien_data_Date11;
    private javax.swing.JLabel nhanVien_data_Date12;
    private javax.swing.JLabel nhanVien_data_Date8;
    private javax.swing.JLabel nhanVien_data_Date9;
    private javax.swing.JLabel nhanVien_data_ID10;
    private javax.swing.JLabel nhanVien_data_ID11;
    private javax.swing.JLabel nhanVien_data_ID12;
    private javax.swing.JLabel nhanVien_data_ID8;
    private javax.swing.JLabel nhanVien_data_ID9;
    private javax.swing.JLabel nhanVien_data_Level10;
    private javax.swing.JLabel nhanVien_data_Level11;
    private javax.swing.JLabel nhanVien_data_Level12;
    private javax.swing.JLabel nhanVien_data_Level8;
    private javax.swing.JLabel nhanVien_data_Level9;
    private javax.swing.JLabel nhanVien_data_Name10;
    private javax.swing.JLabel nhanVien_data_Name11;
    private javax.swing.JLabel nhanVien_data_Name12;
    private javax.swing.JLabel nhanVien_data_Name8;
    private javax.swing.JLabel nhanVien_data_Name9;
    private javax.swing.JLabel nhanVien_data_SDT10;
    private javax.swing.JLabel nhanVien_data_SDT11;
    private javax.swing.JLabel nhanVien_data_SDT12;
    private javax.swing.JLabel nhanVien_data_SDT8;
    private javax.swing.JLabel nhanVien_data_SDT9;
    private javax.swing.JLabel nhanVien_data_Sex10;
    private javax.swing.JLabel nhanVien_data_Sex11;
    private javax.swing.JLabel nhanVien_data_Sex12;
    private javax.swing.JLabel nhanVien_data_Sex8;
    private javax.swing.JLabel nhanVien_data_Sex9;
    private javax.swing.JButton nhanVien_function_Delete10;
    private javax.swing.JButton nhanVien_function_Delete11;
    private javax.swing.JButton nhanVien_function_Delete12;
    private javax.swing.JButton nhanVien_function_Delete8;
    private javax.swing.JButton nhanVien_function_Delete9;
    private javax.swing.JButton nhanVien_function_Detail10;
    private javax.swing.JButton nhanVien_function_Detail11;
    private javax.swing.JButton nhanVien_function_Detail12;
    private javax.swing.JButton nhanVien_function_Detail8;
    private javax.swing.JButton nhanVien_function_Detail9;
    private javax.swing.JButton nhanVien_function_Edit10;
    private javax.swing.JButton nhanVien_function_Edit11;
    private javax.swing.JButton nhanVien_function_Edit12;
    private javax.swing.JButton nhanVien_function_Edit8;
    private javax.swing.JButton nhanVien_function_Edit9;
    private javax.swing.JButton nhanVien_funtion_Add10;
    private javax.swing.JButton nhanVien_funtion_Add11;
    private javax.swing.JButton nhanVien_funtion_Add12;
    private javax.swing.JButton nhanVien_funtion_Add8;
    private javax.swing.JButton nhanVien_funtion_Add9;
    private javax.swing.JPanel nhanVien_showData_tbP;
    private javax.swing.JPanel nhanVien_showList_container;
    private javax.swing.JPanel nhanVien_showList_tbP;
    private javax.swing.JPanel showList_nav;
    // End of variables declaration//GEN-END:variables
}
